---
## Default Kibana configuration from kibana-docker.
## https://github.com/elastic/kibana-docker/blob/master/.tedi/template/kibana.yml.j2
#
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#

#elasticsearch.username: kibana
#elasticsearch.password: 1KH29ygzXV9EJYJh5D06
elasticsearch.username: elastic
elasticsearch.password: Ha9F2GCfkEnLnPRi9C7c
